### ISSUE TITLE
pip fails to install filelock 3.0.11 on python2.7

### ISSUE THREAD

**Issue by cas--** [tox-dev/filelock#52]
Latest update breaks pip install on python2.7 and breaks installing `tox` for testing so rather a critical issue!

```
Collecting filelock<4,>=3.0.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/ce/e1/7d404a13ed831b178a5af635c8b4923fcdff269925cb5839949edf11bd19/filelock-3.0.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-CYvThf/filelock/setup.py", line 42, in <module>
        license_ = open("LICENSE.rst").read()
    IOError: [Errno 2] No such file or directory: 'LICENSE.rst'
```

**Comment by AdorablePotato** [comment]
I removed v3.0.11 for now from PyPi, since I currently have some issues uploading the small fix which is already in the master.

-- Sorry for the inconvenience.

See also: https://github.com/benediktschmitt/py-filelock/commit/df9ced46b7dfdba93a5a41142b09ed6900d5f34c

EDIT: Also removed the tag from GitHub.

**Comment by cas--** [comment]
Thanks for super quick response, all good with Travis tests :)

I didn't know about this lib before and it might be useful :+1:
